[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = { version = "1.4", features = ["with-bytes"]  }
futures = "0.1"
grpcio = "0.2"
bytes = "0.4"
